package com.resyst.vk.core

/**
 * r11: the emoji panel's catalog — every fully-qualified emoji of Unicode 18.0, in the Unicode
 * groups and order (EC1), parsed from assets/emoji/emoji.txt (generated by scripts/gen_emoji.py
 * from the pinned emoji-test.txt). Pure JVM: the service hands in the asset text.
 *
 * A [Cell] is one grid position: the base emoji plus its skin-tone variants (single tones first,
 * then multi-person mixed tones), offered by long-press (EC2). Malformed lines and unknown groups
 * are skipped, never thrown (EC4). The view still drops glyphs the device font lacks (EC5).
 */
class EmojiCatalog private constructor(val groups: List<Group>) {
    data class Cell(val base: String, val tones: List<String>)
    data class Group(val id: String, val label: String, val icon: String, val cells: List<Cell>)

    private val byEmoji = HashMap<String, Cell>().also { m ->
        for (g in groups) for (c in g.cells) { m[c.base] = c; for (t in c.tones) m[t] = c }
    }

    /** The cell an emoji (base or toned variant) belongs to, or null if it is not in the catalog. */
    fun cellOf(e: String): Cell? = byEmoji[e]

    val baseCount: Int get() = groups.sumOf { it.cells.size }
    val variantCount: Int get() = groups.sumOf { g -> g.cells.sumOf { it.tones.size } }

    companion object {
        /** Tab label (Spanish, also the TalkBack name) and tab icon per generator group id, in Unicode order. */
        val GROUPS: List<Triple<String, String, String>> = listOf(
            Triple("caras", "Caras y emociones", "😀"),
            Triple("personas", "Personas y cuerpo", "👋"),
            Triple("naturaleza", "Animales y naturaleza", "🐶"),
            Triple("comida", "Comida y bebida", "🍕"),
            Triple("viajes", "Viajes y lugares", "🚗"),
            Triple("actividades", "Actividades", "⚽"),
            Triple("objetos", "Objetos", "💡"),
            Triple("simbolos", "Símbolos", "✅"),
            Triple("banderas", "Banderas", "🏁"),
        )

        val EMPTY = EmojiCatalog(emptyList())

        fun parse(text: String): EmojiCatalog {
            val cells = LinkedHashMap<String, ArrayList<Cell>>()
            val seen = HashSet<String>()
            var current: ArrayList<Cell>? = null
            for (raw in text.lineSequence()) {
                val line = raw.trim()
                // comments are "# …": a bare '#' prefix would swallow the keycap #️⃣ (EC1)
                if (line.isEmpty() || line == "#" || line.startsWith("# ")) continue
                if (line.startsWith("@")) {
                    val id = line.substring(1)
                    current = if (GROUPS.any { it.first == id }) cells.getOrPut(id) { ArrayList() } else null
                    continue
                }
                val list = current ?: continue
                val parts = line.split(' ').filter { it.isNotEmpty() }
                val base = parts.first()
                if (!EmojiRecents.valid(base) || !seen.add(base)) continue
                val tones = parts.drop(1).filter { EmojiRecents.valid(it) && it != base && seen.add(it) }
                list += Cell(base, tones)
            }
            return EmojiCatalog(GROUPS.mapNotNull { (id, label, icon) ->
                cells[id]?.takeIf { it.isNotEmpty() }?.let { Group(id, label, icon, it) }
            })
        }
    }
}

/**
 * r11: the skin tone the user chose per emoji (ET1): a tone picked by long-press becomes that
 * emoji's default in the grid; picking the plain form clears it. On-device only (the service
 * stores it in files/personal/, wiped by "Borrar lo aprendido", never written from incognito or
 * secret fields — ET2). [decode] keeps only pairs the catalog confirms (ET3).
 */
class EmojiTones {
    private val chosen = LinkedHashMap<String, String>()

    /** The emoji to show / commit for the cell of [base]: its chosen tone, or [base]. */
    fun shown(base: String): String = chosen[base] ?: base

    fun get(base: String): String? = chosen[base]

    /** [pick] (a variant of [cell], or its base to clear) becomes the default. True when it changed. */
    fun choose(cell: EmojiCatalog.Cell, pick: String): Boolean = when (pick) {
        cell.base -> chosen.remove(cell.base) != null
        in cell.tones -> chosen.put(cell.base, pick) != pick
        else -> false
    }

    fun size(): Int = chosen.size

    fun encode(): String = chosen.entries.joinToString("\n") { "${it.key}$SEP${it.value}" }

    companion object {
        private const val SEP = "\t"

        fun decode(s: String?, catalog: EmojiCatalog): EmojiTones {
            val t = EmojiTones()
            for (line in s?.lineSequence() ?: emptySequence()) {
                val parts = line.split(SEP)
                if (parts.size != 2) continue
                val cell = catalog.cellOf(parts[0]) ?: continue
                if (cell.base == parts[0] && parts[1] in cell.tones) t.chosen[cell.base] = parts[1]
            }
            return t
        }
    }
}
