#!/usr/bin/env python3
"""✦ Resyst VK — generate the emoji catalog asset from the pinned Unicode emoji-test.txt.

Input (pinned, offline): scripts/data/emoji-test-18.0.txt (Unicode Emoji 18.0, sha256 checked).
Output: app/src/main/assets/emoji/emoji.txt, parsed by core/EmojiCatalog.kt.

Format (UTF-8, one record per line, lines starting with '# ' are comments — not a bare '#',
which is how the keycap #️⃣ starts):
  @<group-id>                 starts a tab (Unicode group order; Component is dropped)
  <base>[ <variant>...]       one grid cell: the fully-qualified base emoji, then its skin-tone
                              variants (single-tone sequences in Unicode order, then multi-person
                              mixed tones) separated by single spaces

Every fully-qualified emoji appears exactly once: either as a base or as a variant of the base it
reduces to once skin-tone modifiers (U+1F3FB..U+1F3FF) are removed. Minimally-qualified and
unqualified lines are skipped (they are the same emoji without the presentation selector).

Usage: scripts/gen_emoji.py [--check]   (--check: exit 1 if the asset differs from a fresh run)
"""
import hashlib
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SRC = os.path.join(ROOT, 'scripts', 'data', 'emoji-test-18.0.txt')
SHA = '8f3735cda1f92a779d78af67cf86066bb1f07143dc22f2ac29394d9bc57ab21a'
DST = os.path.join(ROOT, 'app', 'src', 'main', 'assets', 'emoji', 'emoji.txt')

GROUPS = {
    'Smileys & Emotion': 'caras',
    'People & Body': 'personas',
    'Animals & Nature': 'naturaleza',
    'Food & Drink': 'comida',
    'Travel & Places': 'viajes',
    'Activities': 'actividades',
    'Objects': 'objetos',
    'Symbols': 'simbolos',
    'Flags': 'banderas',
}
TONES = set(range(0x1F3FB, 0x1F400))


def generate():
    raw = open(SRC, 'rb').read()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != SHA:
        sys.exit(f'{SRC}: sha256 {digest} != pinned {SHA}')
    groups = []  # [(id, [base, ...])]
    resolved = {}  # base -> [variant, ...]
    group = None
    last = None  # the last base seen: CLDR order lists every toned form right after its base
    toned = []
    for line in raw.decode('utf-8').splitlines():
        if line.startswith('# group:'):
            name = line.split(':', 1)[1].strip()
            group = GROUPS.get(name)
            last = None
            if group is not None:
                groups.append((group, []))
            elif name != 'Component':
                sys.exit(f'unknown group {name!r}: update GROUPS (and the Spanish labels in EmojiCatalog.kt)')
            continue
        if line.startswith('# subgroup:'):
            last = None
        if not line.strip() or line.startswith('#') or group is None:
            continue
        cps, rest = line.split(';', 1)
        if rest.split('#', 1)[0].strip() != 'fully-qualified':
            continue
        cp = [int(x, 16) for x in cps.split()]
        s = ''.join(map(chr, cp))
        if any(c in TONES for c in cp):
            if last is None:
                sys.exit(f'toned sequence before any base in its subgroup: {s!r}')
            resolved.setdefault(last, []).append(s)
            toned.append((s, last))
        else:
            groups[-1][1].append(s)
            last = s
    # guard: a toned form whose untoned sequence is itself a base must sit under THAT base
    # (👍🏽 under 👍, ✌🏽 under ✌️); mixed-person forms (🫱🏻‍🫲🏼, 🧑🏻‍❤️‍💋‍🧑🏼) have no untoned
    # RGI twin and stay under the base they follow (🤝, 💏)
    bases = {b for _, items in groups for b in items}
    def strip(v):
        return ''.join(ch for ch in v if ord(ch) not in TONES)
    for v, base in toned:
        u = strip(v)
        cands = {u, u[:1] + '\uFE0F' + u[1:], u[:2] + '\uFE0F' + u[2:]} & bases
        if cands and base not in cands:
            sys.exit(f'{v!r} filed under {base!r} but its base is {cands}')
    # single-tone first (Unicode order), then multi-person mixed tones
    for k, vs in resolved.items():
        single = [v for v in vs if sum(1 for ch in v if ord(ch) in TONES) == 1]
        multi = [v for v in vs if v not in single]
        resolved[k] = single + multi
    out = ['# Generated by scripts/gen_emoji.py from scripts/data/emoji-test-18.0.txt (Unicode Emoji 18.0,',
           f'# sha256 {SHA}). Do not edit by hand.',
           '# © Unicode, Inc. — Unicode License v3, see scripts/data/LICENSE-Unicode.txt.',
           '# @group starts a tab; each line = base emoji [space-separated skin-tone variants].']
    nb = nv = 0
    for gid, items in groups:
        out.append('@' + gid)
        for b in items:
            vs = resolved.get(b, [])
            out.append(' '.join([b] + vs))
            nb += 1
            nv += len(vs)
    return '\n'.join(out) + '\n', nb, nv, {g: len(i) for g, i in groups}


def main():
    text, nb, nv, per = generate()
    if '--check' in sys.argv:
        cur = open(DST, encoding='utf-8').read() if os.path.exists(DST) else ''
        if cur != text:
            print('emoji.txt is stale: run scripts/gen_emoji.py')
            return 1
        print(f'emoji.txt up to date: {nb} bases + {nv} tone variants = {nb + nv}')
        return 0
    os.makedirs(os.path.dirname(DST), exist_ok=True)
    open(DST, 'w', encoding='utf-8').write(text)
    print(f'{os.path.relpath(DST, ROOT)}: {nb} bases + {nv} tone variants = {nb + nv} fully-qualified; {per}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
